name: Discord Bot Runner

on:
  workflow_dispatch:  # Ручной запуск
  schedule:
    - cron: '0 */6 * * *'  # Запускать каждые 6 часов
  push:
    branches: [ main ]

jobs:
  run-bot:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        
    - name: Restore dependencies
      run: dotnet restore bot/bot.csproj
      
    - name: Build
      run: dotnet build bot/bot.csproj --no-restore --configuration Release
      
    - name: Run Discord Bot
      env:
        DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
      run: |
        echo "🚀 Запуск Discord бота на GitHub Actions..."
        echo "Бот будет работать 6 часов (лимит GitHub)"
        cd bot
        timeout 6h dotnet run --configuration Release || true
        echo "⏱️ Время вышло, перезапуск через 10 минут..."